In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense,Flatten
from keras.optimizers import rmsprop
from keras.layers.convolutional import *
from keras.callbacks import EarlyStopping, ReduceLROnPlateau,ModelCheckpoint
from sklearn.metrics import mean_squared_error
        

Using TensorFlow backend.


# Loading Tranning Data 

In [2]:
data_data = pd.read_csv('/home/nitin/Desktop/keras-regression-master/database/train/train_100k.csv') #'../database/train/train_100k.csv'


In [3]:
data_data.head(2)

id         x0          y0         x1         y1          x2          y2  \
0   0  29.379006 -177.906597  66.239362 -143.49507 -107.178287 -338.177166   
1   1 -42.192600  116.207765  81.428046  -94.91560  -68.070200  154.431135   

          x3          y3         x4  ...          x5          y5          x6  \
0  22.166375 -185.843612  84.694131  ...  136.901770  -81.681363  -84.118333   
1  87.454642 -119.361432 -86.614036  ...  -40.894683  123.924804  111.751223   

           y6          x7          y7         x8          y8         x9  \
0 -334.626033 -100.681489 -336.766765 -37.043301 -253.037134   0.695548   
1 -139.521058   15.587590   -0.594559 -19.313860   70.677833 -53.806709   

           y9  
0 -211.044600  
1  133.994773  

[2 rows x 21 columns]

# Loading Ground Truth for Tranning Data 


In [4]:
data_labels = pd.read_csv("/home/nitin/Desktop/keras-regression-master//database/train/train_100k.truth.csv") # '../database/train/train_100k.truth.csv'


In [5]:
data_labels.head(2)

id     slope   intercept
0   0  1.132627 -219.723905
1   1 -1.847354   40.482329

# Loading Test data set 

In [6]:
data_test = pd.read_csv("/home/nitin/Desktop/keras-regression-master/database/test/test_100k.csv") # '../database/test/test_100k.csv'
 

In [7]:
data_test.head(2)

id         x0          y0         x1          y1         x2          y2  \
0   0  71.222322  108.068811 -18.007281  237.215087  -3.841226  204.741403   
1   1  -3.214690   12.107857 -25.870974   48.638382  58.614339  -52.683957   

          x3          y3         x4  ...         x5          y5         x6  \
0 -58.849720  260.483835 -52.056002  ...  11.751514  200.906386 -72.994373   
1  -7.681873   10.727864  59.550048  ... -22.436669   26.141211 -41.874875   

           y6         x7         y7         x8          y8         x9  \
0  288.208877  93.297193  69.952999 -47.006169  262.735790  40.499569   
1   61.856665   5.690588   2.823426  13.122010  -11.562005 -63.664182   

           y9  
0  159.883677  
1   76.761295  

[2 rows x 21 columns]

In [8]:
train_data = data_data.values
train_data[0]

array([   0.        ,   29.37900571, -177.90659732,   66.23936185,
       -143.49507023, -107.17828725, -338.17716559,   22.16637465,
       -185.84361204,   84.6941314 , -130.54795596,  136.90176958,
        -81.68136257,  -84.11833255, -334.62603307, -100.68148866,
       -336.76676483,  -37.04330138, -253.03713404,    0.69554829,
       -211.04459974])

In [9]:
train_labels = data_labels.values
train_labels[0]


array([   0.        ,    1.13262672, -219.72390509])

In [10]:
td = train_data[:, 1:]

print(td.shape)
td[0]


(100000, 20)


array([  29.37900571, -177.90659732,   66.23936185, -143.49507023,
       -107.17828725, -338.17716559,   22.16637465, -185.84361204,
         84.6941314 , -130.54795596,  136.90176958,  -81.68136257,
        -84.11833255, -334.62603307, -100.68148866, -336.76676483,
        -37.04330138, -253.03713404,    0.69554829, -211.04459974])

In [11]:
td = td.reshape(td.shape[0], td.shape[1], 1)
print(td.shape)

(100000, 20, 1)


In [12]:
tl = train_labels[:, 1:]
tl[0]

array([   1.13262672, -219.72390509])

In [13]:
test_data = data_test.values[:, 1:]
test_data[0]

array([ 71.2223217 , 108.06881074, -18.00728057, 237.21508658,
        -3.84122624, 204.74140346, -58.84972014, 260.48383521,
       -52.056002  , 271.4469372 ,  11.75151377, 200.90638634,
       -72.99437307, 288.20887701,  93.29719257,  69.95299883,
       -47.00616922, 262.7357902 ,  40.4995692 , 159.8836771 ])

In [14]:
test_data = test_data.reshape(test_data.shape[0], test_data.shape[1], 1)
print(test_data.shape)

(100000, 20, 1)


In [15]:
xtrain, xtest, ytrain, ytest=train_test_split(td,tl, test_size=0.15)


<IPython.core.display.Javascript object>

# Creating Model using CNN with conv1D

In [16]:
model = Sequential()
model.add(Conv1D(32, 2, activation="relu", input_shape=(20,1)))
model.add(Flatten())
model.add(Dense(64, activation="linear"))
model.add(Dense(2))

In [17]:


opt = keras.optimizers.rmsprop(learning_rate=0.01)




model.compile(optimizer=opt, loss='mse', metrics=['acc', 'mae'])




    

<IPython.core.display.Javascript object>

In [18]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_1 (Conv1D)            (None, 19, 32)            96        
_________________________________________________________________
flatten_1 (Flatten)          (None, 608)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 64)                38976     
_________________________________________________________________
dense_2 (Dense)              (None, 2)                 130       
Total params: 39,202
Trainable params: 39,202
Non-trainable params: 0
_________________________________________________________________


# Setting Callback Functions

In [19]:
earlystop = EarlyStopping(patience=10)

In [20]:
learning_rate_reduction = ReduceLROnPlateau(monitor='val_acc', 
                                            patience=2, 
                                            verbose=1, 
                                            factor=0.5, 
                                            min_lr=0.00001)

In [21]:
filepath = "saved-model-{val_acc:.2f}.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=1, save_best_only=False, mode='max')

In [22]:
callbacks = [earlystop,learning_rate_reduction,checkpoint]

In [23]:
history = model.fit(xtrain,ytrain, epochs=100, verbose=2,callbacks=callbacks,validation_split=0.3)

Train on 59499 samples, validate on 25501 samples
Epoch 1/3
 - 3s - loss: 5226.9097 - acc: 0.9384 - mae: 23.8598 - val_loss: 3322.2007 - val_acc: 0.9415 - val_mae: 29.9300

Epoch 00001: saving model to saved-model-0.94.hdf5
Epoch 2/3
 - 3s - loss: 1758.7030 - acc: 0.9476 - mae: 18.7729 - val_loss: 1720.7656 - val_acc: 0.9458 - val_mae: 17.8637

Epoch 00002: saving model to saved-model-0.95.hdf5
Epoch 3/3
 - 3s - loss: 1726.2824 - acc: 0.9474 - mae: 18.5641 - val_loss: 2554.7392 - val_acc: 0.9400 - val_mae: 23.1261

Epoch 00003: saving model to saved-model-0.94.hdf5


In [24]:
Accuracy = history.history['acc']
Val_Accuracy = history.history['val_acc']



In [25]:
Accuracy =  Accuracy.pop()
Val_Accuracy = Val_Accuracy.pop()
print("Accuracy",Accuracy)
print("Val_Accuracy ",Val_Accuracy) 

Accuracy 0.94736046
Val_Accuracy  0.939963161945343


In [28]:
ypred = model.predict(xtest)
print(model.evaluate(xtrain, ytrain))
print("MSE: %.4f" % mean_squared_error(ytest, ypred))



85000/85000 [==============================] - 2s 18us/step
[2525.322230985754, 0.939764678478241, 22.8852596282959]
MSE: 2476.8295


In [29]:
result_test = model.predict(test_data)

In [30]:
result_test_dataframe = pd.DataFrame(result_test, columns=['slope', 'intercept'])

In [31]:
result_test_dataframe.index.name = 'id'

In [32]:
result_test_dataframe.to_csv("result.csv")